package edu.jyu.stumgm.entity;
// Generated 2017-12-21 20:45:50 by Hibernate Tools 4.0.1.Final

/**
 * StuCou generated by hbm2java
 */
public class StuCou implements java.io.Serializable {

	private Integer id;
	private TeacCou teacCou;
	private Student student;

	public StuCou() {
	}

	public StuCou(Student student, TeacCou teacCou) {
		this.student = student;
		this.teacCou = teacCou;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TeacCou getTeacCou() {
		return this.teacCou;
	}

	public void setTeacCou(TeacCou teacCou) {
		this.teacCou = teacCou;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

}
