package edu.jyu.stumgm.entity;
// Generated 2017-12-21 20:45:50 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TeacCou generated by hbm2java
 */
public class TeacCou implements java.io.Serializable {

	private int id;
	private Teacher teacher;
	private Course course;
	//一个老师授课  id 对应stucous 表的多条记录，也就是多个学生选 
	private Set stuCous = new HashSet(0);

	public TeacCou() {
	}


	public TeacCou(int id, Teacher teacher, Course course) {
		this.id = id;
		this.teacher = teacher;
		this.course = course;
	}

	public TeacCou(int id, Teacher teacher, Course course, Set stuCous) {
		this.id = id;
		this.teacher = teacher;
		this.course = course;
		this.stuCous = stuCous;
	}
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}
	public Set getStuCous() {
		return this.stuCous;
	}

	public void setStuCous(Set stuCous) {
		this.stuCous = stuCous;
	}

}
